.code   PAGO    k103_5
"Nro. Cuenta: %s"
"Nro. Cuenta ?"

.code   PAGO    k103_3
"Nro. Cuenta: %s"
"Nro. Cuenta ?"

.code PAGO k103_11
         "%08s"
         "Nro. de DNI: "

.code PAGO k103_12
         "%08s"
         "Nro. de DNI: "

.code PAGO k103_13
         "%08s"
         "Nro. de DNI: "

.code PAGO k103_14
         "%08s"
         "Nro. de DNI: "
        
.code PAGO k103_15
         "%08s"
         "Nro. de DNI: "

.code PAGO k103_16
         "%08s"
         "Nro. de DNI: "

.code PAGO k103_17
         "%08s"
         "Nro. de DNI: "

.code PAGO k103_18
         "%08s"
         "Nro. de DNI: "

.code PAGO k103_19
         "%08s"
         "Nro. de DNI: "

.code PAGO k103_20
         "%08s"
         "Nro. de DNI: "

.code PAGO k103_21
         "%08s"
         "Nro. de DNI: "

.code PAGO k103_22
         "%08s"
         "Nro. de DNI: "
        
.code PAGO k103_23
         "%08s"
         "Nro. de DNI: "
        
.code PAGO k103_24
         "%08s"
         "Nro. de DNI: "

.code PAGO k103_25
         "%08s"
         "Nro. de DNI: "
        
.code PAGO k103_26
         "%08s"
         "Nro. de DNI: "
        
.code PAGO k103_27
         "%08s"
         "Nro. de DNI: "
        
.code PAGO k103_28
         "%08s"
         "Nro. de DNI: "
        
.code PAGO k103_29
         "%08s"
         "Nro. de DNI: "
        
.code PAGO k103_30
         "%08s"
         "Nro. de DNI: "

.code PAGO k103_31
         "%08s"
         "Nro. de DNI: "

.code PAGO k103_34
         "%08s"
         "Nro. de DNI: "

.code PAGO k103_35
         "%08s"
         "Nro. de DNI: "

.code PAGO k103_36
         "%08s"
         "Nro. de DNI: "

.code PAGO k103_37
         "%08s"
         "Nro. de DNI: "

.code PAGO k103_38
         "%08s"
         "Nro. de DNI: "

.code PAGO k103_39
         "%08s"
         "Nro. de DNI: "
        
.code PAGO k103_40
         "%08s"
         "Nro. de DNI: "
        
.code PAGO k103_41
         "%08s"
         "Nro. de DNI: "

.code PAGO k103_42
         "%08s"
         "Nro. de DNI: "

.code PAGO k103_43
         "%08s"
         "Nro. de DNI: "

.code PAGO k103_44
         "%08s"
         "Nro. de DNI: "

.code PAGO k103_45
         "%08s"
         "Nro. de DNI: "

.code PAGO k103_46
         "%08s"
         "Nro. de DNI: "

.code PAGO k103_47
         "%08s"
         "Nro. de DNI: "

.code PAGO k103_48
         "%08s"
         "Nro. de DNI: "

.code PAGO k103_49
         "%08s"
         "Nro. de DNI: "

.code   PAGO    k103_51
         "%08s"
"Nro. de ORDEN ?"

.code PAGO k103_53
         "%08s"
         "Nro. de DNI: "

.code PAGO k103_54
         "%08s"
         "Nro. de DNI: "

.code PAGO k103_55
         "%08s"
         "Nro. de DNI: "

.code PAGO k103_56
         "%08s"
         "Nro. de DNI: "

.code PAGO k103_57
         "%08s"
         "Nro. de DNI: "

.code PAGO k103_58
         "%08s"
         "Nro. de DNI: "

.code PAGO k103_59
         "%08s"
         "Nro. de DNI: "
        
.code PAGO k103_60
         "%08s"
         "Nro. de DNI: "

.code PAGO k103_61
         "%08s"
         "Nro. de DNI: "

.code PAGO k103_62
         "%08s"
         "Nro. de DNI: "
        
.code PAGO k103_63
         "%08s"
         "Nro. de DNI: "
        
.code PAGO k103_64
         "%08s"
         "Nro. de DNI: "

.code PAGO k103_65
         "%08s"
         "Nro. de DNI: "

.code PAGO k103_66
         "%08s"
         "Nro. de DNI: "

.code PAGO k103_67
         "%08s"
         "Nro. de DNI: "

.code PAGO k103_68
         "%08s"
         "Nro. de DNI: "

.code PAGO k103_69
         "%08s"
         "Nro. de DNI: "

.code PAGO k103_70
         "%08s"
         "Nro. de DNI: "

.code PAGO k103_72
         "%08s"
         "Nro. de DNI: "

.code PAGO k103_73
         "%08s"
         "Nro. de DNI: "

.code PAGO k103_74
         "%08s"
         "Nro. de DNI: "

.code PAGO k103_75
         "%08s"
         "Nro. de DNI: "

.code PAGO k103_102
         "%08s"
         "Nro. de DNI: "

.code PAGO k103_103
         "%08s"
         "Nro. de DNI: "

.code PAGO k103_125
         "%08s"
         "Nro. de DNI: "

.code PAGO k103_126
         "%08s"
         "Nro. de DNI: "

.code PAGO k103_127
         "%08s"
         "Nro. de DNI: "

.code PAGO k103_127
         "%08s"
         "Nro. de DNI: "

.code PAGO k103_128
         "%08s"
         "Nro. de DNI: "

.code PAGO k103_129
         "%08s"
         "Nro. de DNI: "

.code PAGO k103_130
         "%08s"
         "Nro. de DNI: "

.code PAGO k103_131
         "%08s"
         "Nro. de DNI: "

.code PAGO k103_132
         "%08s"
         "Nro. de DNI: "

.code PAGO k103_133
         "%08s"
         "Nro. de DNI: "

.code PAGO k103_134
         "%08s"
         "Nro. de DNI: "

.code PAGO k103_135
         "%08s"
         "Nro. de DNI: "

.code PAGO k103_136
         "%08s"
         "Nro. de DNI: "

.code PAGO k103_137
         "%08s"
         "Nro. de DNI: "

.code PAGO k103_138
         "%08s"
         "Nro. de DNI: "

.code PAGO k103_139
         "%08s"
         "Nro. de DNI: "

.code PAGO k103_140
         "%08s"
         "Nro. de DNI: "

.code PAGO k103_141
         "%08s"
         "Nro. de DNI: "

.code PAGO k103_142
         "%08s"
         "Nro. de DNI: "

.code PAGO k103_143
         "%08s"
         "Nro. de DNI: "

.code PAGO k103_144
         "%08s"
         "Nro. de DNI: "

.code PAGO k103_145
         "%08s"
         "Nro. de DNI: "

.code PAGO k103_146
         "%08s"
         "Nro. de DNI: "

.code PAGO k103_147
         "%08s"
         "Nro. de DNI: "

.code PAGO k103_148
         "%08s"
         "Nro. de DNI: "

.code PAGO k103_149
         "%08s"
         "Nro. de DNI: "
